## Set the delay in seconds for starting
## the watchdog (default: 60).
## Useful for giving the PC time to boot.

start_delay: 60

## Set the delay in seconds for resuming
## the miner after Applications are closed (default: 0).

resume_delay: 0

## Set, in seconds, how often an application
## check should be performed (default: 5).

check_delay: 5

## Specify the full path to the miner.
## REQUIRED -- Please change:

path: 'C:\CryptoMining\miner\miner.exe'

## Specify command line argument for miner.
## Set as empty string if no argument (i.e. '' ).
## REQUIRED -- Please change:

arg: '-c config.txt'

## Specify MSI Afterburner profile to use
## when not mining.
## Remove the # to enable.

#normal_prof: 'Profile1'

## Specify MSI Afterburner profile to use when mining.
## Remove the # to enable.

#mining_prof: 'Profile2'

## Specify Applications that should force the miner
## to stop (ex: "- Photoshop.exe").
## Case does not matter (i.e. "- Photoshop.exe" is
## the same as "- PhOtOsHoP.eXe").

apps:
  - 'Application1.exe'
  - 'Application2.exe'
  - 'Application3.exe'